{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zelgius.android-libraries",
    "module": "bitmap-ktx",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "hvq42vlddfebdmpr2wesluenzq"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "bitmap-ktx-1.0.0.aar",
          "url": "bitmap-ktx-1.0.0.aar",
          "size": 31038,
          "sha512": "02d3f3c01d98df439417d48f34a261336f4985e9095ea91fa3ec1075871ea2a138115fb8172b617523dfea98635e8d5c4c269eb271f8d0752a99f528aa3f7deb",
          "sha256": "27b5ba49b9dabc3ec72f0a33f791e528aaa068d9f0aa1a2d54a71c8095cb29cb",
          "sha1": "2a50458e2e5527fc48bc27c50edeb06e340264ab",
          "md5": "04a5be283003b4eb0a3e307d660e694d"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.0-rc"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "bitmap-ktx-1.0.0.aar",
          "url": "bitmap-ktx-1.0.0.aar",
          "size": 31038,
          "sha512": "02d3f3c01d98df439417d48f34a261336f4985e9095ea91fa3ec1075871ea2a138115fb8172b617523dfea98635e8d5c4c269eb271f8d0752a99f528aa3f7deb",
          "sha256": "27b5ba49b9dabc3ec72f0a33f791e528aaa068d9f0aa1a2d54a71c8095cb29cb",
          "sha1": "2a50458e2e5527fc48bc27c50edeb06e340264ab",
          "md5": "04a5be283003b4eb0a3e307d660e694d"
        }
      ]
    }
  ]
}
