{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zelgius.android-libraries",
    "module": "bitmap-ktx",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "vple4hwjozg4vdvfrrvup77lfa"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "bitmap-ktx-1.0.0.aar",
          "url": "bitmap-ktx-1.0.0.aar",
          "size": 31037,
          "sha512": "3b1100b497c8fdaa29cfa2005fec1cb885931798e123a69a8a292de122d5d4154949f3fb95841e2ba0fade9354aee9b11f0943c155273def46d68c108e016299",
          "sha256": "2d24b3adc5adc02868f61c0f079a5e29bf5dcc1e7686b39afd95a8ad661f2b5d",
          "sha1": "a1216a98f78df8e6996ec1c111580e4c7a9bb8bf",
          "md5": "e612258ef0046735eef9d01704430164"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.0-rc"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "bitmap-ktx-1.0.0.aar",
          "url": "bitmap-ktx-1.0.0.aar",
          "size": 31037,
          "sha512": "3b1100b497c8fdaa29cfa2005fec1cb885931798e123a69a8a292de122d5d4154949f3fb95841e2ba0fade9354aee9b11f0943c155273def46d68c108e016299",
          "sha256": "2d24b3adc5adc02868f61c0f079a5e29bf5dcc1e7686b39afd95a8ad661f2b5d",
          "sha1": "a1216a98f78df8e6996ec1c111580e4c7a9bb8bf",
          "md5": "e612258ef0046735eef9d01704430164"
        }
      ]
    }
  ]
}
