{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zelgius.android-libraries",
    "module": "view-helper-extensions",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4-rc-2",
      "buildId": "snyfpvau6rb5tnj23qux2656vy"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "3.6.3"
          }
        }
      ],
      "files": [
        {
          "name": "view-helper-extensions-1.0.1.aar",
          "url": "view-helper-extensions-1.0.1.aar",
          "size": 27271,
          "sha512": "aaa7af174a5c9ee372fd8c700a564dadc1d7d28097fddbc5cac8eb13256fdb8c10a8d4d894f87d3a242d0ae4ed56ccb193b3653e127b93d07d61d61dbc8e2d4e",
          "sha256": "501c5bbaf0a0edc9c65495564b5b65debf55569d669f2ab66c5d84f3960a185c",
          "sha1": "ce8e72ccd863066598d98408af36586a6083e22e",
          "md5": "4c682e1d144ad3e9e13507bcb781e12d"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "3.6.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "view-helper-extensions-1.0.1.aar",
          "url": "view-helper-extensions-1.0.1.aar",
          "size": 27271,
          "sha512": "aaa7af174a5c9ee372fd8c700a564dadc1d7d28097fddbc5cac8eb13256fdb8c10a8d4d894f87d3a242d0ae4ed56ccb193b3653e127b93d07d61d61dbc8e2d4e",
          "sha256": "501c5bbaf0a0edc9c65495564b5b65debf55569d669f2ab66c5d84f3960a185c",
          "sha1": "ce8e72ccd863066598d98408af36586a6083e22e",
          "md5": "4c682e1d144ad3e9e13507bcb781e12d"
        }
      ]
    }
  ]
}
