{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zelgius.android-libraries",
    "module": "livedataextensions",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "vple4hwjozg4vdvfrrvup77lfa"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "livedataextensions-1.1.0.aar",
          "url": "livedataextensions-1.1.0.aar",
          "size": 4032,
          "sha512": "4d56e58b11a1ae561b6f200299cb1d12d4528383869141da0ed85fe4ab2c9ce0d62790e506a88805452e58255f323a3a003522cfa05f6dde45607e3da05f12b1",
          "sha256": "569a66200bf33e79d11da6e1d0e30c9858367c7a99471c0ec7f7fcf76c98b93a",
          "sha1": "5411453739f0162fcbc8077a23ad41dba93f1341",
          "md5": "5f1b5133a2d06897e3fd3e31679ff227"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.0-rc"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.0-rc"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "livedataextensions-1.1.0.aar",
          "url": "livedataextensions-1.1.0.aar",
          "size": 4032,
          "sha512": "4d56e58b11a1ae561b6f200299cb1d12d4528383869141da0ed85fe4ab2c9ce0d62790e506a88805452e58255f323a3a003522cfa05f6dde45607e3da05f12b1",
          "sha256": "569a66200bf33e79d11da6e1d0e30c9858367c7a99471c0ec7f7fcf76c98b93a",
          "sha1": "5411453739f0162fcbc8077a23ad41dba93f1341",
          "md5": "5f1b5133a2d06897e3fd3e31679ff227"
        }
      ]
    }
  ]
}
