{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zelgius.android-libraries",
    "module": "livedataextensions",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4-rc-2",
      "buildId": "ehfdpcvstfcglnf6pcv4b2iqze"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "livedataextensions-1.1.0.aar",
          "url": "livedataextensions-1.1.0.aar",
          "size": 3910,
          "sha512": "ee90ded5056d618a14de49221a5006eb9fd154245850780c4e002c757719dde5697bf2760d67ae9427262114124d3c25fd223051ec9aa3c7bf18e2e8051eb73e",
          "sha256": "98cd809ba18457582e68e10b0fd401fb9d721635a0add3eb395326ec4fce1413",
          "sha1": "25991457d2e38a51f0c693baa8aca6e6d17a0bf2",
          "md5": "35bbd99b201b07eb6978a4c8b57a035e"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "livedataextensions-1.1.0.aar",
          "url": "livedataextensions-1.1.0.aar",
          "size": 3910,
          "sha512": "ee90ded5056d618a14de49221a5006eb9fd154245850780c4e002c757719dde5697bf2760d67ae9427262114124d3c25fd223051ec9aa3c7bf18e2e8051eb73e",
          "sha256": "98cd809ba18457582e68e10b0fd401fb9d721635a0add3eb395326ec4fce1413",
          "sha1": "25991457d2e38a51f0c693baa8aca6e6d17a0bf2",
          "md5": "35bbd99b201b07eb6978a4c8b57a035e"
        }
      ]
    }
  ]
}
