{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zelgius.android-libraries",
    "module": "livedataextensions",
    "version": "1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4-rc-2",
      "buildId": "kphs6bn37bfk3gbid6jqsi2qoa"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "livedataextensions-1.0.5.aar",
          "url": "livedataextensions-1.0.5.aar",
          "size": 3752,
          "sha512": "915abe47afe298ec5b4a183dfb515473a85f420cb108dc773dc031cb602fbe00814ebdf35f08fe98edaea472e119213764c209c30bf3cedd04fbc8333b3fe883",
          "sha256": "76152c679a5483da217c98909073da9328e9ae3c467b8edf9f47639bd10c0cdb",
          "sha1": "8c6390132504571d26887200847baaa2bd456d8f",
          "md5": "88237da62fb66f029137fd1b4897dc09"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "livedataextensions-1.0.5.aar",
          "url": "livedataextensions-1.0.5.aar",
          "size": 3752,
          "sha512": "915abe47afe298ec5b4a183dfb515473a85f420cb108dc773dc031cb602fbe00814ebdf35f08fe98edaea472e119213764c209c30bf3cedd04fbc8333b3fe883",
          "sha256": "76152c679a5483da217c98909073da9328e9ae3c467b8edf9f47639bd10c0cdb",
          "sha1": "8c6390132504571d26887200847baaa2bd456d8f",
          "md5": "88237da62fb66f029137fd1b4897dc09"
        }
      ]
    }
  ]
}
