{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zelgius.android-libraries",
    "module": "DialogExtensions",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "vple4hwjozg4vdvfrrvup77lfa"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "DialogExtensions-1.0.0.aar",
          "url": "DialogExtensions-1.0.0.aar",
          "size": 27006,
          "sha512": "96fbc8b0668568ed589687f48d4b888eb8fea53ddee13e51ca5f95320ce1643325ef3b6da3d4ebfcf866f99672d62ce185753b21c137d4d2b785b8339c1924f7",
          "sha256": "df7df1022ea29a8ffc17481d8daaa3776e9b08781e85f497c9ad1d5393c0f68e",
          "sha1": "384491da824ca26c9c99b0a6377d7501f2445591",
          "md5": "adcc3adbeb0a79a4c028cf2406af2955"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.0-rc"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.0-rc"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "DialogExtensions-1.0.0.aar",
          "url": "DialogExtensions-1.0.0.aar",
          "size": 27006,
          "sha512": "96fbc8b0668568ed589687f48d4b888eb8fea53ddee13e51ca5f95320ce1643325ef3b6da3d4ebfcf866f99672d62ce185753b21c137d4d2b785b8339c1924f7",
          "sha256": "df7df1022ea29a8ffc17481d8daaa3776e9b08781e85f497c9ad1d5393c0f68e",
          "sha1": "384491da824ca26c9c99b0a6377d7501f2445591",
          "md5": "adcc3adbeb0a79a4c028cf2406af2955"
        }
      ]
    }
  ]
}
