{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zelgius.android-libraries",
    "module": "view-helper-extensions",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "vple4hwjozg4vdvfrrvup77lfa"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.2.0-alpha07"
          }
        }
      ],
      "files": [
        {
          "name": "view-helper-extensions-1.0.3.aar",
          "url": "view-helper-extensions-1.0.3.aar",
          "size": 28432,
          "sha512": "5fc783c92f66541e2529585f23032542260d6632cf57a80ae5f3b801af2ec6aa673390c8acf5923fa38a865e658499ce8c48b279eb25ee01de851d03dd3ddb5a",
          "sha256": "bb2497e7b4ccd2604db99df1fbb520ee87414ff5b04d58e0f382bcdf93386c0a",
          "sha1": "d48d2434970ef517402de37c066a1ed4b449bd25",
          "md5": "9f34626ae82ba2070a01906468ecb88a"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.2.0-alpha07"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.0-rc"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.0-rc"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "view-helper-extensions-1.0.3.aar",
          "url": "view-helper-extensions-1.0.3.aar",
          "size": 28432,
          "sha512": "5fc783c92f66541e2529585f23032542260d6632cf57a80ae5f3b801af2ec6aa673390c8acf5923fa38a865e658499ce8c48b279eb25ee01de851d03dd3ddb5a",
          "sha256": "bb2497e7b4ccd2604db99df1fbb520ee87414ff5b04d58e0f382bcdf93386c0a",
          "sha1": "d48d2434970ef517402de37c066a1ed4b449bd25",
          "md5": "9f34626ae82ba2070a01906468ecb88a"
        }
      ]
    }
  ]
}
