{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zelgius.android-libraries",
    "module": "view-helper-extensions",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4-rc-2",
      "buildId": "kjs6pkr4y5fl7d6m52dceix5ti"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "3.6.3"
          }
        }
      ],
      "files": [
        {
          "name": "view-helper-extensions-1.0.3.aar",
          "url": "view-helper-extensions-1.0.3.aar",
          "size": 28302,
          "sha512": "8a7d96de16e5e89ffbdd398fd1c357ee79e98acd59153ad60646f9ddc32a7214005384d14cd3ccfd9c1ceeff005f9cd4464bd9bdc80a3e0d069363e63c150b64",
          "sha256": "efbdb60fd096711ef8e6f9026ce679ac06011f201aaf1b979a73e5b3588e4c91",
          "sha1": "e2d244d51780dc574b84cc2bb2a196d97e7e1cb3",
          "md5": "b9b6e6694f65f53126ada2965d7370d0"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "3.6.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "view-helper-extensions-1.0.3.aar",
          "url": "view-helper-extensions-1.0.3.aar",
          "size": 28302,
          "sha512": "8a7d96de16e5e89ffbdd398fd1c357ee79e98acd59153ad60646f9ddc32a7214005384d14cd3ccfd9c1ceeff005f9cd4464bd9bdc80a3e0d069363e63c150b64",
          "sha256": "efbdb60fd096711ef8e6f9026ce679ac06011f201aaf1b979a73e5b3588e4c91",
          "sha1": "e2d244d51780dc574b84cc2bb2a196d97e7e1cb3",
          "md5": "b9b6e6694f65f53126ada2965d7370d0"
        }
      ]
    }
  ]
}
