{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zelgius.android-libraries",
    "module": "ContextExtensions",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "vple4hwjozg4vdvfrrvup77lfa"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ContextExtensions-1.0.0.aar",
          "url": "ContextExtensions-1.0.0.aar",
          "size": 24496,
          "sha512": "b6cea1083baa02d1af0bd2a1d679df614ed1558a9e0809df0cb7713347242c21fbca2a40bd9abafa60f34661ca562165fd13a8b2f6a2f1a9cd85c6239b28e507",
          "sha256": "e143fb7826280f9604737122968dcd5f8262a3ad063d041c2aa9e80568aa20b6",
          "sha1": "849b6a066cddf29a27cd9e213fcacee7df573884",
          "md5": "ac552f9e38ef8a67c98eab05045bd2b2"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.0-rc"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.0-rc"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ContextExtensions-1.0.0.aar",
          "url": "ContextExtensions-1.0.0.aar",
          "size": 24496,
          "sha512": "b6cea1083baa02d1af0bd2a1d679df614ed1558a9e0809df0cb7713347242c21fbca2a40bd9abafa60f34661ca562165fd13a8b2f6a2f1a9cd85c6239b28e507",
          "sha256": "e143fb7826280f9604737122968dcd5f8262a3ad063d041c2aa9e80568aa20b6",
          "sha1": "849b6a066cddf29a27cd9e213fcacee7df573884",
          "md5": "ac552f9e38ef8a67c98eab05045bd2b2"
        }
      ]
    }
  ]
}
