{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zelgius.android-libraries",
    "module": "view-helper-extensions",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4-rc-2",
      "buildId": "mnay7eub3jh2jmsexp6jjsdoby"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "3.6.3"
          }
        }
      ],
      "files": [
        {
          "name": "view-helper-extensions-1.0.2.aar",
          "url": "view-helper-extensions-1.0.2.aar",
          "size": 28224,
          "sha512": "9735c29025db301fe386bba6b59b189c9b9c588acbaa28d8c7d82726e7040bfdfd5fda97b6b6c3a7762199823c5210916c9a029698036e2874f02f5512559f00",
          "sha256": "5ee2b96f90fdf0782cda482aaba68ad8e77bf5015136bbea172ca5e2dc94b539",
          "sha1": "401752e17ace070afa637252f191142576cfe8b8",
          "md5": "1724f5e51ad1e94ec65a593a0bd7ec3f"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "3.6.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "view-helper-extensions-1.0.2.aar",
          "url": "view-helper-extensions-1.0.2.aar",
          "size": 28224,
          "sha512": "9735c29025db301fe386bba6b59b189c9b9c588acbaa28d8c7d82726e7040bfdfd5fda97b6b6c3a7762199823c5210916c9a029698036e2874f02f5512559f00",
          "sha256": "5ee2b96f90fdf0782cda482aaba68ad8e77bf5015136bbea172ca5e2dc94b539",
          "sha1": "401752e17ace070afa637252f191142576cfe8b8",
          "md5": "1724f5e51ad1e94ec65a593a0bd7ec3f"
        }
      ]
    }
  ]
}
