{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zelgius.android-libraries",
    "module": "livedataextensions",
    "version": "1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "pzqy4n4mqjcqtjkpb2k2ko7b6y"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "livedataextensions-1.1.jar",
          "url": "livedataextensions-1.1.jar",
          "size": 2692,
          "sha512": "76bda49b9d6ad46fe6e09ef70a340e3ef5901ed6ac21160bf53f0f7867d256cc03f8d3d0a3f1c2acd4ea12d690ef8602e34c0df42f7c38a3572c04f1ad57592a",
          "sha256": "845019f91d293de73953927d23b96139821b0c65e8b54fd3ab65e96e78bcd95c",
          "sha1": "9dbe308d718d0e6afb395e15400e0552e4e2387d",
          "md5": "3fa1550b97af83bcbaf8f4ae4844b372"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "livedataextensions-1.1.jar",
          "url": "livedataextensions-1.1.jar",
          "size": 2692,
          "sha512": "76bda49b9d6ad46fe6e09ef70a340e3ef5901ed6ac21160bf53f0f7867d256cc03f8d3d0a3f1c2acd4ea12d690ef8602e34c0df42f7c38a3572c04f1ad57592a",
          "sha256": "845019f91d293de73953927d23b96139821b0c65e8b54fd3ab65e96e78bcd95c",
          "sha1": "9dbe308d718d0e6afb395e15400e0552e4e2387d",
          "md5": "3fa1550b97af83bcbaf8f4ae4844b372"
        }
      ]
    }
  ]
}
